name: CI/CD for React + TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # ou a versão que você está usando

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm run test -- --watch=false --ci --coverage

    - name: Build the app
      run: |
        npm run build

    - name: Deploy to production (exemplo)
      run: |
        # Aqui você pode adicionar o comando para deploy
        # Por exemplo, se estiver usando AWS, Netlify, ou algo similar
        echo "Deploying to production"
